name = "stdin"
version = "1.0.0"

[deployment]
permission = "private"
nodes = 4

[build]
dir = "build"
entry = "stdin_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "stdin.wasm"
command = "npm run build:release"
